"""Database tables.

Four tables, one per concept in the brief:

    players        who played
    game_sessions  one game (status, score, lives, progress)
    rounds         one sequence presented to the user
    responses      the user's evaluated answer to a round

Two database-level guarantees back the "no double scoring" requirement:

* rounds has UNIQUE(session_id, round_number), so a round can't be created twice
* responses has UNIQUE(round_id), so a round can only ever have one scored answer

The repository's compare-and-set on rounds.status is the first line of defence;
these constraints are the backstop if application code ever gets it wrong.
"""

from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Identity,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Primary keys are Postgres BIGINT identity columns, generated by the database.
# SQLite (used only in tests) auto-increments only an INTEGER primary key, so
# the type falls back to INTEGER there; on Postgres it is always BIGINT.
BigId = BigInteger().with_variant(Integer(), "sqlite")


def _pk():
    return mapped_column(BigId, Identity(always=False), primary_key=True)


def utcnow() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    pass


class SessionStatus:
    CREATED = "created"  # row exists, voice call not connected yet
    ACTIVE = "active"  # bot is playing
    COMPLETED = "completed"  # game ended normally (out of lives, won, or user quit)
    ABANDONED = "abandoned"  # call dropped or ended from the API mid-game

    OPEN = (CREATED, ACTIVE)


class RoundStatus:
    PRESENTING = "presenting"  # bot is reading the cards
    AWAITING = "awaiting"  # cards fully heard, waiting for the answer
    CORRECT = "correct"
    INCORRECT = "incorrect"
    ABANDONED = "abandoned"


class Player(Base):
    __tablename__ = "players"

    id: Mapped[int] = _pk()
    name: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    sessions: Mapped[list["GameSession"]] = relationship(back_populates="player")


class GameSession(Base):
    __tablename__ = "game_sessions"

    id: Mapped[int] = _pk()
    player_id: Mapped[int] = mapped_column(BigId, ForeignKey("players.id"), index=True)
    status: Mapped[str] = mapped_column(String(16), default=SessionStatus.CREATED, index=True)
    score: Mapped[int] = mapped_column(Integer, default=0)
    lives: Mapped[int] = mapped_column(Integer)
    rounds_cleared: Mapped[int] = mapped_column(Integer, default=0)
    rounds_played: Mapped[int] = mapped_column(Integer, default=0)
    best_length: Mapped[int] = mapped_column(Integer, default=0)
    won: Mapped[bool] = mapped_column(Boolean, default=False)
    end_reason: Mapped[str | None] = mapped_column(String(32), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)

    player: Mapped[Player] = relationship(back_populates="sessions")
    rounds: Mapped[list["Round"]] = relationship(back_populates="session", order_by="Round.round_number")


class Round(Base):
    __tablename__ = "rounds"
    __table_args__ = (UniqueConstraint("session_id", "round_number", name="uq_round_per_session"),)

    id: Mapped[int] = _pk()
    session_id: Mapped[int] = mapped_column(BigId, ForeignKey("game_sessions.id"), index=True)
    round_number: Mapped[int] = mapped_column(Integer)
    cards: Mapped[list[str]] = mapped_column(JSON)
    length: Mapped[int] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(16), default=RoundStatus.PRESENTING)
    # How many times the cards were read out (replays after interruptions or "repeat").
    times_presented: Mapped[int] = mapped_column(Integer, default=1)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    evaluated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    session: Mapped[GameSession] = relationship(back_populates="rounds")
    response: Mapped["Response | None"] = relationship(back_populates="round", uselist=False)


class Response(Base):
    __tablename__ = "responses"

    id: Mapped[int] = _pk()
    # unique=True: one scored answer per round, enforced by the database.
    round_id: Mapped[int] = mapped_column(BigId, ForeignKey("rounds.id"), unique=True)
    transcript: Mapped[str] = mapped_column(Text)
    heard: Mapped[list[str]] = mapped_column(JSON)
    is_correct: Mapped[bool] = mapped_column(Boolean)
    points: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    round: Mapped[Round] = relationship(back_populates="response")
